#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 83
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_ = 1,
  anon_sym_COMMA = 2,
  aux_sym_STMT_delimiter_token1 = 3,
  anon_sym_TODO_COLONFuncExpr = 4,
  anon_sym_TODO_COLON_m1Expr = 5,
  anon_sym_TODO_DOT_m2Expr_ = 6,
  anon_sym_2 = 7,
  anon_sym_DOT = 8,
  anon_sym_3 = 9,
  anon_sym_Func = 10,
  anon_sym_TODO_COLONOperand = 11,
  sym_nothing = 12,
  anon_sym_4 = 13,
  anon_sym_5 = 14,
  anon_sym_6 = 15,
  anon_sym_7 = 16,
  anon_sym_8 = 17,
  anon_sym_9 = 18,
  anon_sym_10 = 19,
  sym_symbol_s = 20,
  sym_symbol_F = 21,
  sym_symbol__m = 22,
  sym_symbol__c_ = 23,
  sym_comment = 24,
  sym_source_file = 25,
  sym_STMT = 26,
  sym_STMT_delimiter = 27,
  sym_EXPR = 28,
  sym_EXPORT = 29,
  sym_ANY = 30,
  sym__mod2_ = 31,
  sym__mod1 = 32,
  sym_Func = 33,
  sym_atom = 34,
  sym_subject = 35,
  sym_Derv = 36,
  sym_arg = 37,
  sym_subExpr = 38,
  sym_symbol = 39,
  sym_symbol_sl = 40,
  sym_symbol_Fl = 41,
  sym_symbol__ml = 42,
  sym_symbol__cl_ = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym_STMT_delimiter_repeat1 = 45,
  aux_sym_subject_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_] = "⋄",
  [anon_sym_COMMA] = ",",
  [aux_sym_STMT_delimiter_token1] = "STMT_delimiter_token1",
  [anon_sym_TODO_COLONFuncExpr] = "TODO:FuncExpr",
  [anon_sym_TODO_COLON_m1Expr] = "TODO:_m1Expr",
  [anon_sym_TODO_DOT_m2Expr_] = "TODO._m2Expr_",
  [anon_sym_2] = "⇐",
  [anon_sym_DOT] = ".",
  [anon_sym_3] = "‿",
  [anon_sym_Func] = "Func",
  [anon_sym_TODO_COLONOperand] = "TODO:Operand",
  [sym_nothing] = "nothing",
  [anon_sym_4] = "∞",
  [anon_sym_5] = "⍋",
  [anon_sym_6] = "⊑",
  [anon_sym_7] = "˘",
  [anon_sym_8] = "´",
  [anon_sym_9] = "⊸",
  [anon_sym_10] = "○",
  [sym_symbol_s] = "symbol_s",
  [sym_symbol_F] = "symbol_F",
  [sym_symbol__m] = "symbol__m",
  [sym_symbol__c_] = "symbol__c_",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_STMT] = "STMT",
  [sym_STMT_delimiter] = "STMT_delimiter",
  [sym_EXPR] = "EXPR",
  [sym_EXPORT] = "EXPORT",
  [sym_ANY] = "ANY",
  [sym__mod2_] = "_mod2_",
  [sym__mod1] = "_mod1",
  [sym_Func] = "Func",
  [sym_atom] = "atom",
  [sym_subject] = "subject",
  [sym_Derv] = "Derv",
  [sym_arg] = "arg",
  [sym_subExpr] = "subExpr",
  [sym_symbol] = "symbol",
  [sym_symbol_sl] = "symbol_sl",
  [sym_symbol_Fl] = "symbol_Fl",
  [sym_symbol__ml] = "symbol__ml",
  [sym_symbol__cl_] = "symbol__cl_",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_STMT_delimiter_repeat1] = "STMT_delimiter_repeat1",
  [aux_sym_subject_repeat1] = "subject_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_] = anon_sym_,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_STMT_delimiter_token1] = aux_sym_STMT_delimiter_token1,
  [anon_sym_TODO_COLONFuncExpr] = anon_sym_TODO_COLONFuncExpr,
  [anon_sym_TODO_COLON_m1Expr] = anon_sym_TODO_COLON_m1Expr,
  [anon_sym_TODO_DOT_m2Expr_] = anon_sym_TODO_DOT_m2Expr_,
  [anon_sym_2] = anon_sym_2,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_3] = anon_sym_3,
  [anon_sym_Func] = anon_sym_Func,
  [anon_sym_TODO_COLONOperand] = anon_sym_TODO_COLONOperand,
  [sym_nothing] = sym_nothing,
  [anon_sym_4] = anon_sym_4,
  [anon_sym_5] = anon_sym_5,
  [anon_sym_6] = anon_sym_6,
  [anon_sym_7] = anon_sym_7,
  [anon_sym_8] = anon_sym_8,
  [anon_sym_9] = anon_sym_9,
  [anon_sym_10] = anon_sym_10,
  [sym_symbol_s] = sym_symbol_s,
  [sym_symbol_F] = sym_symbol_F,
  [sym_symbol__m] = sym_symbol__m,
  [sym_symbol__c_] = sym_symbol__c_,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_STMT] = sym_STMT,
  [sym_STMT_delimiter] = sym_STMT_delimiter,
  [sym_EXPR] = sym_EXPR,
  [sym_EXPORT] = sym_EXPORT,
  [sym_ANY] = sym_ANY,
  [sym__mod2_] = sym__mod2_,
  [sym__mod1] = sym__mod1,
  [sym_Func] = sym_Func,
  [sym_atom] = sym_atom,
  [sym_subject] = sym_subject,
  [sym_Derv] = sym_Derv,
  [sym_arg] = sym_arg,
  [sym_subExpr] = sym_subExpr,
  [sym_symbol] = sym_symbol,
  [sym_symbol_sl] = sym_symbol_sl,
  [sym_symbol_Fl] = sym_symbol_Fl,
  [sym_symbol__ml] = sym_symbol__ml,
  [sym_symbol__cl_] = sym_symbol__cl_,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_STMT_delimiter_repeat1] = aux_sym_STMT_delimiter_repeat1,
  [aux_sym_subject_repeat1] = aux_sym_subject_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_STMT_delimiter_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_TODO_COLONFuncExpr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TODO_COLON_m1Expr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TODO_DOT_m2Expr_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_3] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TODO_COLONOperand] = {
    .visible = true,
    .named = false,
  },
  [sym_nothing] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_4] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_5] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_6] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_7] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_9] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_10] = {
    .visible = true,
    .named = false,
  },
  [sym_symbol_s] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol_F] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol__m] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol__c_] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_STMT] = {
    .visible = true,
    .named = true,
  },
  [sym_STMT_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_EXPR] = {
    .visible = true,
    .named = true,
  },
  [sym_EXPORT] = {
    .visible = true,
    .named = true,
  },
  [sym_ANY] = {
    .visible = true,
    .named = true,
  },
  [sym__mod2_] = {
    .visible = false,
    .named = true,
  },
  [sym__mod1] = {
    .visible = false,
    .named = true,
  },
  [sym_Func] = {
    .visible = true,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_subject] = {
    .visible = true,
    .named = true,
  },
  [sym_Derv] = {
    .visible = true,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_subExpr] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol_sl] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol_Fl] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol__ml] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol__cl_] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_STMT_delimiter_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subject_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 26,
  [39] = 30,
  [40] = 40,
  [41] = 20,
  [42] = 23,
  [43] = 21,
  [44] = 18,
  [45] = 19,
  [46] = 17,
  [47] = 22,
  [48] = 28,
  [49] = 29,
  [50] = 26,
  [51] = 31,
  [52] = 33,
  [53] = 27,
  [54] = 54,
  [55] = 24,
  [56] = 25,
  [57] = 30,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 63,
  [67] = 63,
  [68] = 63,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 78,
  [80] = 80,
  [81] = 81,
  [82] = 82,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(44);
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(76);
      if (lookahead == ',') ADVANCE(46);
      if (lookahead == '.') ADVANCE(53);
      if (lookahead == 'F') ADVANCE(73);
      if (lookahead == 'T') ADVANCE(69);
      if (lookahead == '_') ADVANCE(41);
      if (lookahead == 180) ADVANCE(63);
      if (lookahead == 183) ADVANCE(58);
      if (lookahead == 728) ADVANCE(62);
      if (lookahead == 8255) ADVANCE(54);
      if (lookahead == 8656) ADVANCE(52);
      if (lookahead == 8734) ADVANCE(59);
      if (lookahead == 8849) ADVANCE(61);
      if (lookahead == 8888) ADVANCE(64);
      if (lookahead == 8900) ADVANCE(45);
      if (lookahead == 9035) ADVANCE(60);
      if (lookahead == 9675) ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(74);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(76);
      if (lookahead == ',') ADVANCE(46);
      if (lookahead == '.') ADVANCE(53);
      if (lookahead == 'F') ADVANCE(73);
      if (lookahead == 'T') ADVANCE(69);
      if (lookahead == '_') ADVANCE(41);
      if (lookahead == 180) ADVANCE(63);
      if (lookahead == 183) ADVANCE(58);
      if (lookahead == 728) ADVANCE(62);
      if (lookahead == 8255) ADVANCE(54);
      if (lookahead == 8656) ADVANCE(52);
      if (lookahead == 8734) ADVANCE(59);
      if (lookahead == 8849) ADVANCE(61);
      if (lookahead == 8888) ADVANCE(64);
      if (lookahead == 8900) ADVANCE(45);
      if (lookahead == 9035) ADVANCE(60);
      if (lookahead == 9675) ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(74);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '#') ADVANCE(76);
      if (lookahead == ',') ADVANCE(46);
      if (lookahead == '.') ADVANCE(53);
      if (lookahead == 'F') ADVANCE(37);
      if (lookahead == 'T') ADVANCE(14);
      if (lookahead == 8255) ADVANCE(54);
      if (lookahead == 8656) ADVANCE(52);
      if (lookahead == 8900) ADVANCE(45);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(76);
      if (lookahead == 'F') ADVANCE(37);
      if (lookahead == 'T') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(76);
      if (lookahead == '_') ADVANCE(41);
      if (lookahead == 180) ADVANCE(63);
      if (lookahead == 728) ADVANCE(62);
      if (lookahead == 8255) ADVANCE(54);
      if (lookahead == 8734) ADVANCE(59);
      if (lookahead == 8849) ADVANCE(61);
      if (lookahead == 8888) ADVANCE(64);
      if (lookahead == 9035) ADVANCE(60);
      if (lookahead == 9675) ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(74);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 5:
      if (lookahead == '1') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == '2') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'D') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 'E') ADVANCE(38);
      END_STATE();
    case 10:
      if (lookahead == 'E') ADVANCE(39);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(40);
      END_STATE();
    case 12:
      if (lookahead == 'F') ADVANCE(36);
      if (lookahead == 'O') ADVANCE(28);
      if (lookahead == '_') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 'O') ADVANCE(28);
      END_STATE();
    case 14:
      if (lookahead == 'O') ADVANCE(8);
      END_STATE();
    case 15:
      if (lookahead == 'O') ADVANCE(7);
      END_STATE();
    case 16:
      if (lookahead == '_') ADVANCE(23);
      END_STATE();
    case 17:
      if (lookahead == '_') ADVANCE(51);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(55);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(11);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(57);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 23:
      if (lookahead == 'm') ADVANCE(6);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(5);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 28:
      if (lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 29:
      if (lookahead == 'p') ADVANCE(35);
      END_STATE();
    case 30:
      if (lookahead == 'p') ADVANCE(33);
      END_STATE();
    case 31:
      if (lookahead == 'p') ADVANCE(34);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(50);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 36:
      if (lookahead == 'u') ADVANCE(25);
      END_STATE();
    case 37:
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 38:
      if (lookahead == 'x') ADVANCE(29);
      END_STATE();
    case 39:
      if (lookahead == 'x') ADVANCE(30);
      END_STATE();
    case 40:
      if (lookahead == 'x') ADVANCE(31);
      END_STATE();
    case 41:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 42:
      if (eof) ADVANCE(44);
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '#') ADVANCE(76);
      if (lookahead == ',') ADVANCE(46);
      if (lookahead == '.') ADVANCE(53);
      if (lookahead == 'F') ADVANCE(37);
      if (lookahead == 'T') ADVANCE(14);
      if (lookahead == 8255) ADVANCE(54);
      if (lookahead == 8656) ADVANCE(52);
      if (lookahead == 8900) ADVANCE(45);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(42)
      END_STATE();
    case 43:
      if (eof) ADVANCE(44);
      if (lookahead == '#') ADVANCE(76);
      if (lookahead == '.') ADVANCE(53);
      if (lookahead == 'F') ADVANCE(73);
      if (lookahead == 'T') ADVANCE(69);
      if (lookahead == '_') ADVANCE(41);
      if (lookahead == 180) ADVANCE(63);
      if (lookahead == 183) ADVANCE(58);
      if (lookahead == 728) ADVANCE(62);
      if (lookahead == 8255) ADVANCE(54);
      if (lookahead == 8656) ADVANCE(52);
      if (lookahead == 8734) ADVANCE(59);
      if (lookahead == 8849) ADVANCE(61);
      if (lookahead == 8888) ADVANCE(64);
      if (lookahead == 9035) ADVANCE(60);
      if (lookahead == 9675) ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(43)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(74);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_STMT_delimiter_token1);
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '\r') ADVANCE(1);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_STMT_delimiter_token1);
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead == '\r') ADVANCE(2);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_TODO_COLONFuncExpr);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_TODO_COLON_m1Expr);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_TODO_DOT_m2Expr_);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_2);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_3);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_Func);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_Func);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_TODO_COLONOperand);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_nothing);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_4);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_5);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_6);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_7);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_8);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_9);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_10);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_symbol_s);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_symbol_F);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == ':') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_symbol_F);
      if (lookahead == 'D') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_symbol_F);
      if (lookahead == 'O') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_symbol_F);
      if (lookahead == 'O') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_symbol_F);
      if (lookahead == 'c') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_symbol_F);
      if (lookahead == 'n') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_symbol_F);
      if (lookahead == 'u') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_symbol_F);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_symbol__m);
      if (lookahead == '_') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(76);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 43},
  [3] = {.lex_state = 43},
  [4] = {.lex_state = 43},
  [5] = {.lex_state = 43},
  [6] = {.lex_state = 43},
  [7] = {.lex_state = 43},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 43},
  [14] = {.lex_state = 43},
  [15] = {.lex_state = 43},
  [16] = {.lex_state = 43},
  [17] = {.lex_state = 43},
  [18] = {.lex_state = 43},
  [19] = {.lex_state = 43},
  [20] = {.lex_state = 43},
  [21] = {.lex_state = 43},
  [22] = {.lex_state = 43},
  [23] = {.lex_state = 43},
  [24] = {.lex_state = 43},
  [25] = {.lex_state = 43},
  [26] = {.lex_state = 43},
  [27] = {.lex_state = 43},
  [28] = {.lex_state = 43},
  [29] = {.lex_state = 43},
  [30] = {.lex_state = 43},
  [31] = {.lex_state = 43},
  [32] = {.lex_state = 43},
  [33] = {.lex_state = 43},
  [34] = {.lex_state = 43},
  [35] = {.lex_state = 43},
  [36] = {.lex_state = 43},
  [37] = {.lex_state = 43},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 42},
  [41] = {.lex_state = 42},
  [42] = {.lex_state = 42},
  [43] = {.lex_state = 42},
  [44] = {.lex_state = 42},
  [45] = {.lex_state = 42},
  [46] = {.lex_state = 42},
  [47] = {.lex_state = 42},
  [48] = {.lex_state = 42},
  [49] = {.lex_state = 42},
  [50] = {.lex_state = 42},
  [51] = {.lex_state = 42},
  [52] = {.lex_state = 42},
  [53] = {.lex_state = 42},
  [54] = {.lex_state = 42},
  [55] = {.lex_state = 42},
  [56] = {.lex_state = 42},
  [57] = {.lex_state = 42},
  [58] = {.lex_state = 42},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 4},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 4},
  [67] = {.lex_state = 4},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 43},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 43},
  [76] = {.lex_state = 43},
  [77] = {.lex_state = 43},
  [78] = {.lex_state = 43},
  [79] = {.lex_state = 43},
  [80] = {.lex_state = 43},
  [81] = {.lex_state = 43},
  [82] = {.lex_state = 43},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_STMT_delimiter_token1] = ACTIONS(1),
    [anon_sym_TODO_COLONFuncExpr] = ACTIONS(1),
    [anon_sym_TODO_COLON_m1Expr] = ACTIONS(1),
    [anon_sym_TODO_DOT_m2Expr_] = ACTIONS(1),
    [anon_sym_2] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_3] = ACTIONS(1),
    [anon_sym_Func] = ACTIONS(1),
    [anon_sym_TODO_COLONOperand] = ACTIONS(1),
    [sym_nothing] = ACTIONS(1),
    [anon_sym_4] = ACTIONS(1),
    [anon_sym_5] = ACTIONS(1),
    [anon_sym_6] = ACTIONS(1),
    [anon_sym_7] = ACTIONS(1),
    [anon_sym_8] = ACTIONS(1),
    [anon_sym_9] = ACTIONS(1),
    [anon_sym_10] = ACTIONS(1),
    [sym_symbol_s] = ACTIONS(1),
    [sym_symbol_F] = ACTIONS(1),
    [sym_symbol__m] = ACTIONS(1),
    [sym_symbol__c_] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(80),
    [sym_STMT] = STATE(61),
    [sym_STMT_delimiter] = STATE(5),
    [sym_EXPR] = STATE(69),
    [sym_EXPORT] = STATE(69),
    [sym_ANY] = STATE(79),
    [sym__mod2_] = STATE(25),
    [sym__mod1] = STATE(25),
    [sym_Func] = STATE(25),
    [sym_atom] = STATE(41),
    [sym_subject] = STATE(54),
    [sym_Derv] = STATE(7),
    [sym_arg] = STATE(64),
    [sym_subExpr] = STATE(70),
    [sym_symbol] = STATE(82),
    [sym_symbol_sl] = STATE(45),
    [sym_symbol_Fl] = STATE(27),
    [sym_symbol__ml] = STATE(25),
    [sym_symbol__cl_] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_STMT_delimiter_repeat1] = STATE(9),
    [anon_sym_] = ACTIONS(5),
    [anon_sym_COMMA] = ACTIONS(5),
    [aux_sym_STMT_delimiter_token1] = ACTIONS(7),
    [anon_sym_TODO_COLONFuncExpr] = ACTIONS(9),
    [anon_sym_TODO_COLON_m1Expr] = ACTIONS(9),
    [anon_sym_TODO_DOT_m2Expr_] = ACTIONS(9),
    [anon_sym_Func] = ACTIONS(11),
    [anon_sym_TODO_COLONOperand] = ACTIONS(13),
    [sym_nothing] = ACTIONS(15),
    [anon_sym_4] = ACTIONS(17),
    [anon_sym_5] = ACTIONS(19),
    [anon_sym_6] = ACTIONS(19),
    [anon_sym_7] = ACTIONS(21),
    [anon_sym_8] = ACTIONS(21),
    [anon_sym_9] = ACTIONS(23),
    [anon_sym_10] = ACTIONS(23),
    [sym_symbol_s] = ACTIONS(25),
    [sym_symbol_F] = ACTIONS(27),
    [sym_symbol__m] = ACTIONS(29),
    [sym_symbol__c_] = ACTIONS(31),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [sym_STMT] = STATE(62),
    [sym_EXPR] = STATE(69),
    [sym_EXPORT] = STATE(69),
    [sym_ANY] = STATE(79),
    [sym__mod2_] = STATE(25),
    [sym__mod1] = STATE(25),
    [sym_Func] = STATE(25),
    [sym_atom] = STATE(41),
    [sym_subject] = STATE(54),
    [sym_Derv] = STATE(7),
    [sym_arg] = STATE(64),
    [sym_subExpr] = STATE(70),
    [sym_symbol] = STATE(82),
    [sym_symbol_sl] = STATE(45),
    [sym_symbol_Fl] = STATE(27),
    [sym_symbol__ml] = STATE(25),
    [sym_symbol__cl_] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_TODO_COLONFuncExpr] = ACTIONS(33),
    [anon_sym_TODO_COLON_m1Expr] = ACTIONS(33),
    [anon_sym_TODO_DOT_m2Expr_] = ACTIONS(33),
    [anon_sym_Func] = ACTIONS(36),
    [anon_sym_TODO_COLONOperand] = ACTIONS(39),
    [sym_nothing] = ACTIONS(42),
    [anon_sym_4] = ACTIONS(45),
    [anon_sym_5] = ACTIONS(48),
    [anon_sym_6] = ACTIONS(48),
    [anon_sym_7] = ACTIONS(51),
    [anon_sym_8] = ACTIONS(51),
    [anon_sym_9] = ACTIONS(54),
    [anon_sym_10] = ACTIONS(54),
    [sym_symbol_s] = ACTIONS(57),
    [sym_symbol_F] = ACTIONS(60),
    [sym_symbol__m] = ACTIONS(63),
    [sym_symbol__c_] = ACTIONS(66),
    [sym_comment] = ACTIONS(69),
  },
  [3] = {
    [sym_STMT] = STATE(59),
    [sym_EXPR] = STATE(69),
    [sym_EXPORT] = STATE(69),
    [sym_ANY] = STATE(79),
    [sym__mod2_] = STATE(25),
    [sym__mod1] = STATE(25),
    [sym_Func] = STATE(25),
    [sym_atom] = STATE(41),
    [sym_subject] = STATE(54),
    [sym_Derv] = STATE(7),
    [sym_arg] = STATE(64),
    [sym_subExpr] = STATE(70),
    [sym_symbol] = STATE(82),
    [sym_symbol_sl] = STATE(45),
    [sym_symbol_Fl] = STATE(27),
    [sym_symbol__ml] = STATE(25),
    [sym_symbol__cl_] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_TODO_COLONFuncExpr] = ACTIONS(71),
    [anon_sym_TODO_COLON_m1Expr] = ACTIONS(71),
    [anon_sym_TODO_DOT_m2Expr_] = ACTIONS(71),
    [anon_sym_Func] = ACTIONS(11),
    [anon_sym_TODO_COLONOperand] = ACTIONS(73),
    [sym_nothing] = ACTIONS(75),
    [anon_sym_4] = ACTIONS(77),
    [anon_sym_5] = ACTIONS(79),
    [anon_sym_6] = ACTIONS(79),
    [anon_sym_7] = ACTIONS(81),
    [anon_sym_8] = ACTIONS(81),
    [anon_sym_9] = ACTIONS(83),
    [anon_sym_10] = ACTIONS(83),
    [sym_symbol_s] = ACTIONS(85),
    [sym_symbol_F] = ACTIONS(27),
    [sym_symbol__m] = ACTIONS(87),
    [sym_symbol__c_] = ACTIONS(31),
    [sym_comment] = ACTIONS(69),
  },
  [4] = {
    [sym_STMT] = STATE(60),
    [sym_EXPR] = STATE(69),
    [sym_EXPORT] = STATE(69),
    [sym_ANY] = STATE(79),
    [sym__mod2_] = STATE(25),
    [sym__mod1] = STATE(25),
    [sym_Func] = STATE(25),
    [sym_atom] = STATE(41),
    [sym_subject] = STATE(54),
    [sym_Derv] = STATE(7),
    [sym_arg] = STATE(64),
    [sym_subExpr] = STATE(70),
    [sym_symbol] = STATE(82),
    [sym_symbol_sl] = STATE(45),
    [sym_symbol_Fl] = STATE(27),
    [sym_symbol__ml] = STATE(25),
    [sym_symbol__cl_] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_TODO_COLONFuncExpr] = ACTIONS(71),
    [anon_sym_TODO_COLON_m1Expr] = ACTIONS(71),
    [anon_sym_TODO_DOT_m2Expr_] = ACTIONS(71),
    [anon_sym_Func] = ACTIONS(11),
    [anon_sym_TODO_COLONOperand] = ACTIONS(73),
    [sym_nothing] = ACTIONS(75),
    [anon_sym_4] = ACTIONS(77),
    [anon_sym_5] = ACTIONS(79),
    [anon_sym_6] = ACTIONS(79),
    [anon_sym_7] = ACTIONS(81),
    [anon_sym_8] = ACTIONS(81),
    [anon_sym_9] = ACTIONS(83),
    [anon_sym_10] = ACTIONS(83),
    [sym_symbol_s] = ACTIONS(85),
    [sym_symbol_F] = ACTIONS(27),
    [sym_symbol__m] = ACTIONS(87),
    [sym_symbol__c_] = ACTIONS(31),
    [sym_comment] = ACTIONS(69),
  },
  [5] = {
    [sym_STMT] = STATE(59),
    [sym_EXPR] = STATE(69),
    [sym_EXPORT] = STATE(69),
    [sym_ANY] = STATE(79),
    [sym__mod2_] = STATE(25),
    [sym__mod1] = STATE(25),
    [sym_Func] = STATE(25),
    [sym_atom] = STATE(41),
    [sym_subject] = STATE(54),
    [sym_Derv] = STATE(7),
    [sym_arg] = STATE(64),
    [sym_subExpr] = STATE(70),
    [sym_symbol] = STATE(82),
    [sym_symbol_sl] = STATE(45),
    [sym_symbol_Fl] = STATE(27),
    [sym_symbol__ml] = STATE(25),
    [sym_symbol__cl_] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(4),
    [anon_sym_TODO_COLONFuncExpr] = ACTIONS(71),
    [anon_sym_TODO_COLON_m1Expr] = ACTIONS(71),
    [anon_sym_TODO_DOT_m2Expr_] = ACTIONS(71),
    [anon_sym_Func] = ACTIONS(11),
    [anon_sym_TODO_COLONOperand] = ACTIONS(73),
    [sym_nothing] = ACTIONS(75),
    [anon_sym_4] = ACTIONS(77),
    [anon_sym_5] = ACTIONS(79),
    [anon_sym_6] = ACTIONS(79),
    [anon_sym_7] = ACTIONS(81),
    [anon_sym_8] = ACTIONS(81),
    [anon_sym_9] = ACTIONS(83),
    [anon_sym_10] = ACTIONS(83),
    [sym_symbol_s] = ACTIONS(85),
    [sym_symbol_F] = ACTIONS(27),
    [sym_symbol__m] = ACTIONS(87),
    [sym_symbol__c_] = ACTIONS(31),
    [sym_comment] = ACTIONS(69),
  },
  [6] = {
    [sym_ANY] = STATE(79),
    [sym__mod2_] = STATE(25),
    [sym__mod1] = STATE(25),
    [sym_Func] = STATE(25),
    [sym_atom] = STATE(41),
    [sym_subject] = STATE(54),
    [sym_Derv] = STATE(7),
    [sym_arg] = STATE(64),
    [sym_subExpr] = STATE(71),
    [sym_symbol_sl] = STATE(45),
    [sym_symbol_Fl] = STATE(27),
    [sym_symbol__ml] = STATE(25),
    [sym_symbol__cl_] = STATE(25),
    [anon_sym_Func] = ACTIONS(11),
    [anon_sym_TODO_COLONOperand] = ACTIONS(73),
    [sym_nothing] = ACTIONS(89),
    [anon_sym_4] = ACTIONS(77),
    [anon_sym_5] = ACTIONS(79),
    [anon_sym_6] = ACTIONS(79),
    [anon_sym_7] = ACTIONS(81),
    [anon_sym_8] = ACTIONS(81),
    [anon_sym_9] = ACTIONS(83),
    [anon_sym_10] = ACTIONS(83),
    [sym_symbol_s] = ACTIONS(91),
    [sym_symbol_F] = ACTIONS(93),
    [sym_symbol__m] = ACTIONS(95),
    [sym_symbol__c_] = ACTIONS(97),
    [sym_comment] = ACTIONS(69),
  },
  [7] = {
    [sym_ANY] = STATE(79),
    [sym__mod2_] = STATE(25),
    [sym__mod1] = STATE(25),
    [sym_Func] = STATE(25),
    [sym_atom] = STATE(41),
    [sym_subject] = STATE(54),
    [sym_Derv] = STATE(7),
    [sym_arg] = STATE(64),
    [sym_subExpr] = STATE(65),
    [sym_symbol_sl] = STATE(45),
    [sym_symbol_Fl] = STATE(27),
    [sym_symbol__ml] = STATE(25),
    [sym_symbol__cl_] = STATE(25),
    [anon_sym_Func] = ACTIONS(11),
    [anon_sym_TODO_COLONOperand] = ACTIONS(73),
    [sym_nothing] = ACTIONS(89),
    [anon_sym_4] = ACTIONS(77),
    [anon_sym_5] = ACTIONS(79),
    [anon_sym_6] = ACTIONS(79),
    [anon_sym_7] = ACTIONS(81),
    [anon_sym_8] = ACTIONS(81),
    [anon_sym_9] = ACTIONS(83),
    [anon_sym_10] = ACTIONS(83),
    [sym_symbol_s] = ACTIONS(91),
    [sym_symbol_F] = ACTIONS(93),
    [sym_symbol__m] = ACTIONS(95),
    [sym_symbol__c_] = ACTIONS(97),
    [sym_comment] = ACTIONS(69),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 1,
      aux_sym_STMT_delimiter_token1,
    STATE(8), 1,
      aux_sym_STMT_delimiter_repeat1,
    ACTIONS(101), 2,
      anon_sym_,
      anon_sym_COMMA,
    ACTIONS(107), 17,
      anon_sym_TODO_COLONFuncExpr,
      anon_sym_TODO_COLON_m1Expr,
      anon_sym_TODO_DOT_m2Expr_,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol_F,
      sym_symbol__m,
      sym_symbol__c_,
  [36] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    ACTIONS(113), 1,
      aux_sym_STMT_delimiter_token1,
    STATE(8), 1,
      aux_sym_STMT_delimiter_repeat1,
    ACTIONS(111), 2,
      anon_sym_,
      anon_sym_COMMA,
    ACTIONS(115), 17,
      anon_sym_TODO_COLONFuncExpr,
      anon_sym_TODO_COLON_m1Expr,
      anon_sym_TODO_DOT_m2Expr_,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol_F,
      sym_symbol__m,
      sym_symbol__c_,
  [72] = 16,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_symbol__m,
    ACTIONS(97), 1,
      sym_symbol__c_,
    ACTIONS(117), 1,
      anon_sym_4,
    ACTIONS(119), 1,
      sym_symbol_s,
    ACTIONS(121), 1,
      sym_symbol_F,
    STATE(19), 1,
      sym_symbol_sl,
    STATE(20), 1,
      sym_atom,
    STATE(27), 1,
      sym_symbol_Fl,
    STATE(32), 1,
      sym_Func,
    STATE(36), 1,
      sym_subject,
    STATE(78), 1,
      sym_ANY,
    ACTIONS(79), 2,
      anon_sym_5,
      anon_sym_6,
    ACTIONS(81), 2,
      anon_sym_7,
      anon_sym_8,
    ACTIONS(83), 2,
      anon_sym_9,
      anon_sym_10,
    STATE(25), 4,
      sym__mod2_,
      sym__mod1,
      sym_symbol__ml,
      sym_symbol__cl_,
  [127] = 14,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_symbol__m,
    ACTIONS(97), 1,
      sym_symbol__c_,
    ACTIONS(117), 1,
      anon_sym_4,
    ACTIONS(119), 1,
      sym_symbol_s,
    ACTIONS(121), 1,
      sym_symbol_F,
    STATE(17), 1,
      sym_atom,
    STATE(19), 1,
      sym_symbol_sl,
    STATE(24), 1,
      sym_ANY,
    STATE(27), 1,
      sym_symbol_Fl,
    ACTIONS(79), 2,
      anon_sym_5,
      anon_sym_6,
    ACTIONS(81), 2,
      anon_sym_7,
      anon_sym_8,
    ACTIONS(123), 2,
      anon_sym_9,
      anon_sym_10,
    STATE(25), 5,
      sym__mod2_,
      sym__mod1,
      sym_Func,
      sym_symbol__ml,
      sym_symbol__cl_,
  [177] = 14,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_4,
    ACTIONS(91), 1,
      sym_symbol_s,
    ACTIONS(131), 1,
      sym_symbol_F,
    ACTIONS(133), 1,
      sym_symbol__m,
    ACTIONS(135), 1,
      sym_symbol__c_,
    STATE(45), 1,
      sym_symbol_sl,
    STATE(46), 1,
      sym_atom,
    STATE(53), 1,
      sym_symbol_Fl,
    STATE(55), 1,
      sym_ANY,
    ACTIONS(125), 2,
      anon_sym_5,
      anon_sym_6,
    ACTIONS(127), 2,
      anon_sym_7,
      anon_sym_8,
    ACTIONS(129), 2,
      anon_sym_9,
      anon_sym_10,
    STATE(56), 5,
      sym__mod2_,
      sym__mod1,
      sym_Func,
      sym_symbol__ml,
      sym_symbol__cl_,
  [227] = 4,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(139), 14,
      anon_sym_TODO_COLONFuncExpr,
      anon_sym_TODO_COLON_m1Expr,
      anon_sym_TODO_DOT_m2Expr_,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [255] = 4,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(139), 14,
      anon_sym_TODO_COLONFuncExpr,
      anon_sym_TODO_COLON_m1Expr,
      anon_sym_TODO_DOT_m2Expr_,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [283] = 4,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(139), 14,
      anon_sym_TODO_COLONFuncExpr,
      anon_sym_TODO_COLON_m1Expr,
      anon_sym_TODO_DOT_m2Expr_,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [311] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(141), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(139), 14,
      anon_sym_TODO_COLONFuncExpr,
      anon_sym_TODO_COLON_m1Expr,
      anon_sym_TODO_DOT_m2Expr_,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [336] = 4,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_DOT,
    ACTIONS(151), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(149), 12,
      anon_sym_3,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [362] = 5,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_3,
    STATE(22), 1,
      aux_sym_subject_repeat1,
    ACTIONS(155), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(157), 11,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [390] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(161), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(159), 13,
      anon_sym_DOT,
      anon_sym_3,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [414] = 5,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_3,
    ACTIONS(163), 1,
      anon_sym_DOT,
    ACTIONS(165), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(167), 11,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [442] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(171), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(169), 13,
      anon_sym_DOT,
      anon_sym_3,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [466] = 5,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_3,
    STATE(22), 1,
      aux_sym_subject_repeat1,
    ACTIONS(176), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(178), 11,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [494] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(182), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(180), 13,
      anon_sym_DOT,
      anon_sym_3,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [518] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(176), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(178), 12,
      anon_sym_3,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [541] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(151), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(149), 12,
      anon_sym_3,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [564] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(186), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(184), 12,
      anon_sym_3,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [587] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(190), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(188), 12,
      anon_sym_3,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [610] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(194), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(192), 12,
      anon_sym_3,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [633] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(198), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(196), 12,
      anon_sym_3,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [656] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(202), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(200), 12,
      anon_sym_3,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [679] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(206), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(204), 12,
      anon_sym_3,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [702] = 4,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_3,
    ACTIONS(208), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(210), 11,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [727] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(214), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(212), 12,
      anon_sym_3,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [750] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(216), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(218), 11,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [772] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(220), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(222), 11,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [794] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(208), 3,
      anon_sym_Func,
      sym_symbol_F,
      sym_symbol__c_,
    ACTIONS(210), 11,
      anon_sym_TODO_COLONOperand,
      sym_nothing,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol__m,
  [816] = 11,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_4,
    ACTIONS(119), 1,
      sym_symbol_s,
    ACTIONS(224), 1,
      sym_symbol__m,
    ACTIONS(226), 1,
      sym_symbol__c_,
    STATE(19), 1,
      sym_symbol_sl,
    STATE(81), 1,
      sym_atom,
    ACTIONS(81), 2,
      anon_sym_7,
      anon_sym_8,
    ACTIONS(83), 2,
      anon_sym_9,
      anon_sym_10,
    STATE(10), 2,
      sym__mod2_,
      sym_symbol__cl_,
    STATE(34), 2,
      sym__mod1,
      sym_symbol__ml,
  [854] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_symbol__c_,
    ACTIONS(184), 11,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol_F,
      sym_symbol__m,
  [874] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(202), 1,
      sym_symbol__c_,
    ACTIONS(200), 11,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_10,
      sym_symbol_s,
      sym_symbol_F,
      sym_symbol__m,
  [894] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_2,
    ACTIONS(159), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(161), 6,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_3,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [913] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_3,
    ACTIONS(230), 1,
      anon_sym_DOT,
    ACTIONS(167), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(165), 4,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [933] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(182), 6,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_3,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [949] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(171), 6,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_3,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [965] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_3,
    STATE(47), 1,
      aux_sym_subject_repeat1,
    ACTIONS(157), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(155), 4,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [985] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(161), 6,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_3,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [1001] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_DOT,
    ACTIONS(149), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(151), 5,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_3,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [1019] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_3,
    STATE(47), 1,
      aux_sym_subject_repeat1,
    ACTIONS(178), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(176), 4,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [1039] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(194), 5,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_3,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [1054] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(198), 5,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_3,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [1069] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(186), 5,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_3,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [1084] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(206), 5,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_3,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [1099] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(214), 5,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_3,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [1114] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(190), 5,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_3,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [1129] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_Func,
    ACTIONS(13), 1,
      anon_sym_TODO_COLONOperand,
    STATE(6), 1,
      sym_Derv,
    ACTIONS(239), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(241), 2,
      anon_sym_,
      anon_sym_COMMA,
  [1150] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(176), 5,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_3,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [1165] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(151), 5,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_3,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [1180] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(202), 5,
      anon_sym_,
      anon_sym_COMMA,
      anon_sym_3,
      anon_sym_Func,
      anon_sym_TODO_COLONOperand,
  [1195] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_Func,
    ACTIONS(13), 1,
      anon_sym_TODO_COLONOperand,
    STATE(6), 1,
      sym_Derv,
    ACTIONS(243), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(245), 2,
      anon_sym_,
      anon_sym_COMMA,
  [1216] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      aux_sym_STMT_delimiter_repeat1,
    STATE(14), 1,
      sym_STMT_delimiter,
    ACTIONS(5), 2,
      anon_sym_,
      anon_sym_COMMA,
  [1236] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      aux_sym_STMT_delimiter_repeat1,
    STATE(13), 1,
      sym_STMT_delimiter,
    ACTIONS(5), 2,
      anon_sym_,
      anon_sym_COMMA,
  [1256] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(247), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      aux_sym_STMT_delimiter_repeat1,
    STATE(15), 1,
      sym_STMT_delimiter,
    ACTIONS(5), 2,
      anon_sym_,
      anon_sym_COMMA,
  [1276] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      aux_sym_STMT_delimiter_token1,
    STATE(9), 1,
      aux_sym_STMT_delimiter_repeat1,
    STATE(16), 1,
      sym_STMT_delimiter,
    ACTIONS(5), 2,
      anon_sym_,
      anon_sym_COMMA,
  [1293] = 5,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym_symbol_s,
    ACTIONS(251), 1,
      sym_symbol_F,
    ACTIONS(253), 1,
      sym_symbol__m,
    ACTIONS(255), 1,
      sym_symbol__c_,
  [1309] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(259), 2,
      anon_sym_,
      anon_sym_COMMA,
  [1321] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(263), 2,
      anon_sym_,
      anon_sym_COMMA,
  [1333] = 5,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(265), 1,
      sym_symbol_s,
    ACTIONS(267), 1,
      sym_symbol_F,
    ACTIONS(269), 1,
      sym_symbol__m,
    ACTIONS(271), 1,
      sym_symbol__c_,
  [1349] = 5,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(265), 1,
      sym_symbol_s,
    ACTIONS(267), 1,
      sym_symbol_F,
    ACTIONS(269), 1,
      sym_symbol__m,
    ACTIONS(273), 1,
      sym_symbol__c_,
  [1365] = 5,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym_symbol_s,
    ACTIONS(267), 1,
      sym_symbol_F,
    ACTIONS(269), 1,
      sym_symbol__m,
    ACTIONS(273), 1,
      sym_symbol__c_,
  [1381] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(245), 2,
      anon_sym_,
      anon_sym_COMMA,
  [1393] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(277), 2,
      anon_sym_,
      anon_sym_COMMA,
  [1405] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(281), 2,
      anon_sym_,
      anon_sym_COMMA,
  [1417] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 2,
      ts_builtin_sym_end,
      aux_sym_STMT_delimiter_token1,
    ACTIONS(285), 2,
      anon_sym_,
      anon_sym_COMMA,
  [1429] = 4,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(265), 1,
      sym_symbol_s,
    ACTIONS(269), 1,
      sym_symbol__m,
    ACTIONS(273), 1,
      sym_symbol__c_,
  [1442] = 4,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_TODO_COLONOperand,
    ACTIONS(287), 1,
      anon_sym_Func,
    STATE(6), 1,
      sym_Derv,
  [1455] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_3,
    ACTIONS(289), 1,
      anon_sym_2,
  [1465] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_2,
    ACTIONS(291), 1,
      anon_sym_3,
  [1475] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_2,
    ACTIONS(293), 1,
      anon_sym_3,
  [1485] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_3,
    STATE(18), 1,
      aux_sym_subject_repeat1,
  [1495] = 3,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(295), 1,
      anon_sym_3,
    STATE(44), 1,
      aux_sym_subject_repeat1,
  [1505] = 2,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(297), 1,
      ts_builtin_sym_end,
  [1512] = 2,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_DOT,
  [1519] = 2,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 36,
  [SMALL_STATE(10)] = 72,
  [SMALL_STATE(11)] = 127,
  [SMALL_STATE(12)] = 177,
  [SMALL_STATE(13)] = 227,
  [SMALL_STATE(14)] = 255,
  [SMALL_STATE(15)] = 283,
  [SMALL_STATE(16)] = 311,
  [SMALL_STATE(17)] = 336,
  [SMALL_STATE(18)] = 362,
  [SMALL_STATE(19)] = 390,
  [SMALL_STATE(20)] = 414,
  [SMALL_STATE(21)] = 442,
  [SMALL_STATE(22)] = 466,
  [SMALL_STATE(23)] = 494,
  [SMALL_STATE(24)] = 518,
  [SMALL_STATE(25)] = 541,
  [SMALL_STATE(26)] = 564,
  [SMALL_STATE(27)] = 587,
  [SMALL_STATE(28)] = 610,
  [SMALL_STATE(29)] = 633,
  [SMALL_STATE(30)] = 656,
  [SMALL_STATE(31)] = 679,
  [SMALL_STATE(32)] = 702,
  [SMALL_STATE(33)] = 727,
  [SMALL_STATE(34)] = 750,
  [SMALL_STATE(35)] = 772,
  [SMALL_STATE(36)] = 794,
  [SMALL_STATE(37)] = 816,
  [SMALL_STATE(38)] = 854,
  [SMALL_STATE(39)] = 874,
  [SMALL_STATE(40)] = 894,
  [SMALL_STATE(41)] = 913,
  [SMALL_STATE(42)] = 933,
  [SMALL_STATE(43)] = 949,
  [SMALL_STATE(44)] = 965,
  [SMALL_STATE(45)] = 985,
  [SMALL_STATE(46)] = 1001,
  [SMALL_STATE(47)] = 1019,
  [SMALL_STATE(48)] = 1039,
  [SMALL_STATE(49)] = 1054,
  [SMALL_STATE(50)] = 1069,
  [SMALL_STATE(51)] = 1084,
  [SMALL_STATE(52)] = 1099,
  [SMALL_STATE(53)] = 1114,
  [SMALL_STATE(54)] = 1129,
  [SMALL_STATE(55)] = 1150,
  [SMALL_STATE(56)] = 1165,
  [SMALL_STATE(57)] = 1180,
  [SMALL_STATE(58)] = 1195,
  [SMALL_STATE(59)] = 1216,
  [SMALL_STATE(60)] = 1236,
  [SMALL_STATE(61)] = 1256,
  [SMALL_STATE(62)] = 1276,
  [SMALL_STATE(63)] = 1293,
  [SMALL_STATE(64)] = 1309,
  [SMALL_STATE(65)] = 1321,
  [SMALL_STATE(66)] = 1333,
  [SMALL_STATE(67)] = 1349,
  [SMALL_STATE(68)] = 1365,
  [SMALL_STATE(69)] = 1381,
  [SMALL_STATE(70)] = 1393,
  [SMALL_STATE(71)] = 1405,
  [SMALL_STATE(72)] = 1417,
  [SMALL_STATE(73)] = 1429,
  [SMALL_STATE(74)] = 1442,
  [SMALL_STATE(75)] = 1455,
  [SMALL_STATE(76)] = 1465,
  [SMALL_STATE(77)] = 1475,
  [SMALL_STATE(78)] = 1485,
  [SMALL_STATE(79)] = 1495,
  [SMALL_STATE(80)] = 1505,
  [SMALL_STATE(81)] = 1512,
  [SMALL_STATE(82)] = 1519,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(70),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(35),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(37),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(58),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(43),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(29),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(28),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(39),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(40),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(75),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(77),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(76),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_STMT_delimiter_repeat1, 2),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_STMT_delimiter_repeat1, 2), SHIFT_REPEAT(8),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_STMT_delimiter_repeat1, 2), SHIFT_REPEAT(8),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_STMT_delimiter_repeat1, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_STMT_delimiter, 1),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_STMT_delimiter, 1),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ANY, 1),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ANY, 1),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subject, 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 2),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom, 1),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atom, 1),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subject, 1),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 1),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol_sl, 1),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol_sl, 1),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subject_repeat1, 2), SHIFT_REPEAT(11),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_subject_repeat1, 2),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subject_repeat1, 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom, 3),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atom, 3),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__mod2_, 3),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__mod2_, 3),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Func, 1),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Func, 1),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol__ml, 1),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol__ml, 1),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol_Fl, 1),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol_Fl, 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol__cl_, 1),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol__cl_, 1),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__mod1, 3),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__mod1, 3),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Derv, 3),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Derv, 3),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Func, 3),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Func, 3),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Derv, 2),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Derv, 2),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Derv, 1),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Derv, 1),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 1),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [236] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_subject_repeat1, 2), SHIFT_REPEAT(12),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 1),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 1),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_STMT, 1),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_STMT, 1),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subExpr, 1),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subExpr, 1),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 2),
  [263] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 2),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [271] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [273] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_EXPR, 1),
  [277] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_EXPR, 1),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 3),
  [281] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 3),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_EXPORT, 2),
  [285] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_EXPORT, 2),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 1),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__mod2_, 1),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__mod1, 1),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [297] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_bqn(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
